update cos region

diff --git a/.blue_green_deploy_pipeline/task.yaml b/.blue_green_deploy_pipeline/task.yaml
--- a/.blue_green_deploy_pipeline/task.yaml
+++ b/.blue_green_deploy_pipeline/task.yaml
@@ -46,77 +46,79 @@ spec:
         - name: COSAPIKEY
           value: $(params.cos-api-key)
         - name: FILE
-          value: inventory.json  
+          value: inventory.json
       script: |
-          #!/bin/bash
+        #!/bin/bash
 
-          # Code here fetches the artifact metadata as present in the inventory.json.
-          # The task assumes the file /output/inventory-repo/inventory.json is already present as a result of the cloning of the 
-          # by the upstream git-clone-inventory-repo task. The JSON file contains the metadata like the name of the name of the artifact (artifact)
-          # the build number (build_number) among other details. 
-          
-          cd /output/inventory-repo;          
-          if [[ -f "$FILE" ]]; then
-            OBJECTNAME=$(cat $FILE |jq -r '.artifact')
-            BUILD=$(cat $FILE |jq -r '.build_number')
-            echo -n "${BUILD}" > $(results.build_number.path)
-            echo -n "${OBJECTNAME}" > $(results.objectname.path)
-          fi
+        # Code here fetches the artifact metadata as present in the inventory.json.
+        # The task assumes the file /output/inventory-repo/inventory.json is already present as a result of the cloning of the 
+        # by the upstream git-clone-inventory-repo task. The JSON file contains the metadata like the name of the name of the artifact (artifact)
+        # the build number (build_number) among other details. 
 
-          # Code here downloads the artifact after processing the information present in the inventory.json.
-          # The downloaded artifacts will be stored in /output directory which can then be utilized by downstream
-          # task to carry out deployment steps on the target Virtual Server instance.
-          cd /output 
-          REGION=$(echo ${COSREGION##*:})
-          if [ -z ${COSAPIKEY} ]; then echo "COSAPIKEY is not set"; COSAPIKEY=$APIKEY; fi;
+        cd /output/inventory-repo;          
+        if [[ -f "$FILE" ]]; then
+          OBJECTNAME=$(cat $FILE |jq -r '.artifact')
+          BUILD=$(cat $FILE |jq -r '.build_number')
+          echo -n "${BUILD}" > $(results.build_number.path)
+          echo -n "${OBJECTNAME}" > $(results.objectname.path)
+        fi
+
+        # Code here downloads the artifact after processing the information present in the inventory.json.
+        # The downloaded artifacts will be stored in /output directory which can then be utilized by downstream
+        # task to carry out deployment steps on the target Virtual Server instance.
+          cd /output
           ibmcloud login -a $API -r $REGION --apikey $COSAPIKEY;
-          ibmcloud plugin install cloud-object-storage;
+          ibmcloud plugin install cloud-object-storage; 
+          REGION=$(ibmcloud cos bucket-class-get --bucket $COSBUCKETNAME | grep -i REGION | awk {'print $2'})
+          if [ -z ${REGION} ]; then 
+            REGION=${COSREGION##*:}
+          fi
+          if [ -z ${COSAPIKEY} ]; then echo "COSAPIKEY is not set"; COSAPIKEY=$APIKEY; fi;
+        #
+        # Function to download the binary artifact from IBM Cloud Object Store
+        # 
+        DownloadFromCOS() {
+          echo "Check if the Bucket with name $COSBUCKETNAME exists"
+          if [ "$(ibmcloud cos bucket-head --bucket "$COSBUCKETNAME" --region $REGION | awk {'print $1'} |head -n 1)" == "OK" ]; then
+              echo "Started downloading of artifacts from IBM Cloud Object Storage"
+              ibmcloud cos object-get --bucket "$COSBUCKETNAME" --key ${OBJECTNAME} ${OBJECTNAME}
+              echo "Finished downloading of artifacts from IBM Cloud Object Storage"
+          else
+              echo "Invalid cos-bucket-name for retreving artifacts"
+              exit 1;
+          fi
+        }
 
-          #
-          # Function to download the binary artifact from IBM Cloud Object Store
-          # 
-          DownloadFromCOS() {
-            echo "Check if the Bucket with name $COSBUCKETNAME exists"
-            if [ "$(ibmcloud cos bucket-head --bucket "$COSBUCKETNAME" --region $REGION | awk {'print $1'} |head -n 1)" == "OK" ]; then
-                echo "Started downloading of artifacts from IBM Cloud Object Storage"
-                ibmcloud cos object-get --bucket "$COSBUCKETNAME" --key ${OBJECTNAME} ${OBJECTNAME}
-                echo "Finished downloading of artifacts from IBM Cloud Object Storage"
-            else
-                echo "Invalid cos-bucket-name for retreving artifacts"
-                exit 1;
-            fi
-          }
+        #
+        # Function to download the binary artifact from Artifactory
+        # 
+        DownloadFromArtifactory() {
+          USERID=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.user_id')
+          TOKEN=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.token')
+          REPO=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.release_url')
+          echo "Started downloading of artifacts from Artifactory"
+          curl -u $USERID:$TOKEN "$REPO/$OBJECTNAME" --output $OBJECTNAME
+          echo "Finished downloading of artifacts from Artifactory"
+        }
 
-          #
-          # Function to download the binary artifact from Artifactory
-          # 
-          DownloadFromArtifactory() {
-            USERID=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.user_id')
-            TOKEN=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.token')
-            REPO=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.release_url')
-            echo "Started downloading of artifacts from Artifactory"
-            curl -u $USERID:$TOKEN "$REPO/$OBJECTNAME" --output $OBJECTNAME
-            echo "Finished downloading of artifacts from Artifactory"
-          }
-
-          #
-          # Driver Function to download the binary artifact
-          # The function:
-          #   Checks if the Artifactory Integration exists. If yes then it downloads the artifacts from Artifactory.
-          #   If no then it downloads the artifacts from IBM Cloud Object Storage.
-          # 
-          if [ -n "$ARTIFACTORY" ]; then
-            if jq -e . >/dev/null 2>&1 <<<"$ARTIFACTORY"; then
-              echo "Artifactory Configuration found in the toolchain."
-              DownloadFromArtifactory
-            else
-              echo "Artifactory Configuration not found in the toolchain. Proceeding with Cloud Object Storage."
-              DownloadFromCOS
-            fi
+        #
+        # Driver Function to download the binary artifact
+        # The function:
+        #   Checks if the Artifactory Integration exists. If yes then it downloads the artifacts from Artifactory.
+        #   If no then it downloads the artifacts from IBM Cloud Object Storage.
+        # 
+        if [ -n "$ARTIFACTORY" ]; then
+          if jq -e . >/dev/null 2>&1 <<<"$ARTIFACTORY"; then
+            echo "Artifactory Configuration found in the toolchain."
+            DownloadFromArtifactory
           else
             echo "Artifactory Configuration not found in the toolchain. Proceeding with Cloud Object Storage."
             DownloadFromCOS
           fi
+        else
+          echo "Artifactory Configuration not found in the toolchain. Proceeding with Cloud Object Storage."
+          DownloadFromCOS
+        fi
 ---
 apiVersion: tekton.dev/v1beta1
 kind: Task
@@ -151,7 +153,7 @@ spec:
     - name: bastion-host-user-name
       description: Bastion Host User Name
     - name: bastion-host-ssh-keys
-      description: Bastion host 
+      description: Bastion host
     - name: blue-pool
       description: Blue Pool for Blue Green Deployemnt
     - name: deployment-strategy
@@ -161,11 +163,11 @@ spec:
     - name: loadbalancer
       description: Load Balancer Name
     - name: pool-ssh-keys
-      description: Blue and Green Pool base64 encoded private SSH key 
-    - name: pool-user-name   
+      description: Blue and Green Pool base64 encoded private SSH key
+    - name: pool-user-name
       description: Blue and Green Pool User Name
     - name: commons-hosted-region
-      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"                  
+      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"
   workspaces:
     - name: output
       description: A workspace
@@ -200,23 +202,23 @@ spec:
         - name: BASTION_HOST
           value: $(params.bastion-host)
         - name: BASTION_HOST_USER_NAME
-          value: $(params.bastion-host-user-name)        
+          value: $(params.bastion-host-user-name)
         - name: BASTION_HOST_SSH_KEYS
-          value: $(params.bastion-host-ssh-keys)      
+          value: $(params.bastion-host-ssh-keys)
         - name: BLUE_POOL
-          value: $(params.blue-pool)                 
+          value: $(params.blue-pool)
         - name: GREEN_POOL
-          value: $(params.green-pool)          
+          value: $(params.green-pool)
         - name: LOAD_BALANCER_NAME
-          value: $(params.loadbalancer)                   
+          value: $(params.loadbalancer)
         - name: DEPLLOYMENT_STRATEGY
-          value: $(params.deployment-strategy)                
+          value: $(params.deployment-strategy)
         - name: POOL_SSH_KEYS
-          value: $(params.pool-ssh-keys)         
+          value: $(params.pool-ssh-keys)
         - name: POOL_USER_NAME
           value: $(params.pool-user-name)
         - name: commons-hosted-region
-          value: $(params.commons-hosted-region)                     
+          value: $(params.commons-hosted-region)
       script: |
         #!/bin/bash
         # This step logs into the Virtual Server Instance based on the credentials provided during the Toolchain creation.
@@ -250,7 +252,7 @@ spec:
       description: the IBM Cloud api endpoint
       default: "https://cloud.ibm.com"
     - name: apikey
-      description: The IBM Cloud API Key  
+      description: The IBM Cloud API Key
     - name: inventory-repo
       description: The variable storing git integration for the repository storing build inventory with the toolchain
     - name: scripts-subpath
@@ -260,7 +262,7 @@ spec:
     - name: bastion-host-user-name
       description: Bastion Host User Name
     - name: bastion-host-ssh-keys
-      description: Bastion host 
+      description: Bastion host
     - name: blue-pool
       description: Blue Pool for Blue Green Deployemnt
     - name: deployment-strategy
@@ -270,13 +272,13 @@ spec:
     - name: loadbalancer
       description: Load Balancer Name
     - name: pool-ssh-keys
-      description: Blue and Green Pool base64 encoded private SSH key 
-    - name: pool-user-name   
-      description: Blue and Green Pool User Name         
+      description: Blue and Green Pool base64 encoded private SSH key
+    - name: pool-user-name
+      description: Blue and Green Pool User Name
   workspaces:
     - name: output
       description: A workspace
-      mountPath: /output  
+      mountPath: /output
   steps:
     - name: acceptance-test
       image: ibmcom/pipeline-base-image:2.11
@@ -287,29 +289,29 @@ spec:
         - name: API
           value: $(params.api)
         - name: APIKEY
-          value: $(params.apikey)       
+          value: $(params.apikey)
         - name: INVENTORY_REPO
           value: $(params.inventory-repo)
         - name: scripts-subpath
-          value: $(params.scripts-subpath)     
+          value: $(params.scripts-subpath)
         - name: BASTION_HOST
           value: $(params.bastion-host)
         - name: BASTION_HOST_USER_NAME
-          value: $(params.bastion-host-user-name)        
+          value: $(params.bastion-host-user-name)
         - name: BASTION_HOST_SSH_KEYS
-          value: $(params.bastion-host-ssh-keys)      
+          value: $(params.bastion-host-ssh-keys)
         - name: BLUE_POOL
-          value: $(params.blue-pool)                 
+          value: $(params.blue-pool)
         - name: GREEN_POOL
-          value: $(params.green-pool)          
+          value: $(params.green-pool)
         - name: LOAD_BALANCER_NAME
-          value: $(params.loadbalancer)       
+          value: $(params.loadbalancer)
         - name: DEPLLOYMENT_STRATEGY
-          value: $(params.deployment-strategy)                        
+          value: $(params.deployment-strategy)
         - name: POOL_SSH_KEYS
-          value: $(params.pool-ssh-keys)         
+          value: $(params.pool-ssh-keys)
         - name: POOL_USER_NAME
-          value: $(params.pool-user-name)                       
+          value: $(params.pool-user-name)
       script: |
         #!/bin/bash
         subpath="$(params.scripts-subpath)"
@@ -328,7 +330,7 @@ spec:
       description: the IBM Cloud api endpoint
       default: "https://cloud.ibm.com"
     - name: apikey
-      description: The IBM Cloud API Key  
+      description: The IBM Cloud API Key
     - name: scripts-subpath
       description: The subpath to the script repo from root
     - name: blue-pool
@@ -340,11 +342,11 @@ spec:
     - name: deployment-strategy
       description: Deployment Strategy
     - name: commons-hosted-region
-      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"                   
+      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"
   workspaces:
     - name: output
       description: A workspace
-      mountPath: /output  
+      mountPath: /output
   steps:
     - name: prod-release
       image: ibmcom/pipeline-base-image:2.11
@@ -355,19 +357,19 @@ spec:
         - name: API
           value: $(params.api)
         - name: APIKEY
-          value: $(params.apikey)      
+          value: $(params.apikey)
         - name: scripts-subpath
-          value: $(params.scripts-subpath)      
+          value: $(params.scripts-subpath)
         - name: BLUE_POOL
-          value: $(params.blue-pool)                 
+          value: $(params.blue-pool)
         - name: GREEN_POOL
-          value: $(params.green-pool)          
+          value: $(params.green-pool)
         - name: LOAD_BALANCER_NAME
           value: $(params.loadbalancer)
         - name: DEPLLOYMENT_STRATEGY
           value: $(params.deployment-strategy)
         - name: commons-hosted-region
-          value: $(params.commons-hosted-region)                                                    
+          value: $(params.commons-hosted-region)
       script: |
         #!/bin/bash
         source <(curl -sSL "$(params.commons-hosted-region)/scripts/deployment_strategies/blue_green/vsi/switch-blue-green.sh")
