remove cos region

diff --git a/.build_pipeline/task.yaml b/.build_pipeline/task.yaml
--- a/.build_pipeline/task.yaml
+++ b/.build_pipeline/task.yaml
@@ -59,8 +59,6 @@ spec:
       default: "https://cloud.ibm.com"
     - name: apikey
       description: The IBM Cloud API Key
-    - name: cos-region
-      description: The IBM Cloud Region in which Cloud Object Storage Instance in created
     - name: cos-bucket-name
       description: The Cloud Object Storage Bucket name where build artifact will be stored
     - name: cos-api-key
@@ -95,8 +93,6 @@ spec:
           value: $(params.cos-api-key)
         - name: COSBUCKETNAME
           value: $(params.cos-bucket-name)
-        - name: COSREGION
-          value: $(params.cos-region)
         - name: OBJECTNAME
           value: $(params.objectname)
         - name: ARTIFACTORY
@@ -150,23 +146,19 @@ spec:
           #    
           CheckAndCreateBucket() {
             echo "Bucket Name to be used by toolchain is" $COSBUCKETNAME
-            if ibmcloud cos bucket-head --bucket "$COSBUCKETNAME" --region $REGION ; then
-              echo "Bucket already exists."
+            TOOLCHAINGUID=$(ibmcloud resource service-instance "$INSTANCENAME" --id)
+            TRIMMEDGUID=$(echo $TOOLCHAINGUID | tr -d '\n')
+            SERVICEID=$(echo $TRIMMEDGUID | awk '{print $NF}')
+            echo "Bucket does not exist. Proceeding with creation."
+            if ibmcloud cos bucket-create --bucket "$COSBUCKETNAME" --ibm-service-instance-id $SERVICEID ; then
+              echo "Bucket with name $COSBUCKETNAME created successfully."
+              SetBucketExpiration
+              echo "Bucket with name $COSBUCKETNAME configured successfully."
             else
-              TOOLCHAINGUID=$(ibmcloud resource service-instance "$INSTANCENAME" --id)
-              TRIMMEDGUID=$(echo $TOOLCHAINGUID | tr -d '\n')
-              SERVICEID=$(echo $TRIMMEDGUID | awk '{print $NF}')
-              echo "Bucket does not exist. Proceeding with creation."
-              if ibmcloud cos bucket-create --bucket "$COSBUCKETNAME" --ibm-service-instance-id $SERVICEID ; then
-                echo "Bucket with name $COSBUCKETNAME created successfully."
-                SetBucketExpiration
-                echo "Bucket with name $COSBUCKETNAME configured successfully."
-              else
-                echo "Received Bucket Name with invalid characters."
-                echo "Please ensure that Bucket Name must start and end in alphanumeric characters (3 to 63)."
-                echo "Also ensure that characters allowed are lowercase, numbers and non-consecutive dots and hyphens."
-                exit 1;
-              fi
+              echo "Received Bucket Name with invalid characters."
+              echo "Please ensure that Bucket Name must start and end in alphanumeric characters (3 to 63)."
+              echo "Also ensure that characters allowed are lowercase, numbers and non-consecutive dots and hyphens."
+              exit 1;
             fi
           }
 
@@ -177,6 +169,7 @@ spec:
           # 2. User has only one COS Instance, The user could be on Lite Plan. We will reuse the same instance for the creating the bucket.
           # 3. User has two or more COS Instances, Create a COS instance where the name of the instance will be same as the toolchain name and use it for creating the bucket. This will help the user to easily identify the bucket in which the artifacts will be stored.
           CheckAndCreateCOSInstance() {
+            echo "Bucket Name to be used by toolchain is" $COSBUCKETNAME
             COS_INSTANCE_COUNT=$(ibmcloud resource service-instances --service-name cloud-object-storage | awk {'print $1'} | awk 'NR>3' | wc -l)
             if [ "$COS_INSTANCE_COUNT" -eq "1" ]; then
               INSTANCENAME=$(ibmcloud resource service-instances --output JSON --service-name cloud-object-storage | jq .[0] | jq -r .name)
@@ -205,26 +198,23 @@ spec:
           #   Uploads the artifacts to the bucket within the instance.
           # 
           UploadToCOStorage() {
+            if [ -z ${COSAPIKEY} ]; then echo "COSAPIKEY is not given, Using default APIKEY"; COSAPIKEY=$APIKEY; fi;          
             RESOURCEGROUP=$(cat /cd-config/toolchain.json | jq -r '.container.guid');
             ibmcloud login -a $API -r $REGION --apikey $COSAPIKEY;
             ibmcloud plugin install cloud-object-storage;
-            REGION=$(ibmcloud cos bucket-class-get --bucket $COSBUCKETNAME | grep -i REGION | awk {'print $2'})
-            if [ -z ${REGION} ]; then 
-              REGION=${COSREGION##*:}
+            if ibmcloud cos bucket-class-get --bucket $COSBUCKETNAME 2>/dev/null ; then
+              REGION=$(ibmcloud cos bucket-class-get --bucket $COSBUCKETNAME | grep -i REGION | awk {'print $2'})
+              ibmcloud login -a $API -r $REGION --apikey $COSAPIKEY; 
+            else  
+              COSENDPOINT="s3.${REGION}.cloud-object-storage.appdomain.cloud";
+              echo "Target the resource group with ID ${RESOURCEGROUP}"
+              #ibmcloud target -g ${RESOURCEGROUP} 
+              echo "Check if IBM Cloud Object Storage Instance already exists"
+              CheckAndCreateCOSInstance
+              echo "Check if the Bucket required to store artifacts already exists"
+              CheckAndCreateBucket
             fi
             COSENDPOINT="s3.${REGION}.cloud-object-storage.appdomain.cloud";
-            COSAPIKEYFLAG=${COSAPIKEY};
-            if [ -z ${COSAPIKEY} ]; then echo "COSAPIKEY is not given, Using default APIKEY"; COSAPIKEY=$APIKEY; fi;
-            if [ -z ${COSAPIKEYFLAG} ]; then
-            echo "Target the resource group with ID ${RESOURCEGROUP}"
-            ibmcloud target -g ${RESOURCEGROUP}
-                
-            echo "Check if IBM Cloud Object Storage Instance already exists"
-            CheckAndCreateCOSInstance
-
-            echo "Check if the Bucket required to store artifacts already exists"
-            CheckAndCreateBucket
-            fi
             echo "Started uploading of artifacts to Cloud Object Storage"
             ibmcloud cos object-put --bucket $COSBUCKETNAME --key ${OBJECTNAME} --body ${OBJECTNAME}
             echo "Finished uploading of artifacts to Cloud Object Storage"
