Merging changes to anamika's branch (#1)
* Speed Up Maven Builds

* Reducing unit-test runtime

* Speed up with MAVEN_OPTS

* Passing MAVEN_OPTS

* Improve build timings

* .

* .

* Use maven local repo

* Offline build

* .

* .

* Merge from upstream

* update tutorial link (#19)

* Update the UI with COS instance details (#20)

* Update Readme file with GitOps Flow and Build/Deploy Flow (#18)

* Speed Up Maven Builds

* Reducing unit-test runtime

* Speed up with MAVEN_OPTS

* Passing MAVEN_OPTS

* Improve build timings

* .

* .

* Use maven local repo

* Offline build

* .

* .

* Merge from upstream

* Update Readme

* Add GitOps Flow

* Update Readme.

* Update README with build and deploy documentation

* Adding ToC

* Incorporate review comments.

* Incorporate Review Comments.

* Adding pipeline repository to build

* Check root contents.

* Correct the git-clone-task

* Add subpath

* Correcting mount point

* Clone the pipeline repo to subpath.

* Fix the empty name field

* Fix directory exists issue.

* Remove debug

* Content of current directory

* Update Readme (#16)

Co-authored-by: Piyush <80688956+mundrapiyush36@users.noreply.github.com>

* Support multiple COS instances scenario (#15)

The following are the scenarios.

1. If user does not have any COS instance, Then toolchain will create a COS instance in `Lite Plan` with name as toolchain name and use it for further bucket creation.
2. if user has only one Instance, Then we assume that user is on `Lite Plan`. We will not create a new instance but re-use the same instance for the bucket creation.
3.  if user has more then Instance, Then we will create a COS instance with the name of the instance will be toolchain name and use it for further bucket creation.

* Revert dirty commit (#21)

* Speed Up Maven Builds

* Reducing unit-test runtime

* Speed up with MAVEN_OPTS

* Passing MAVEN_OPTS

* Improve build timings

* .

* .

* Use maven local repo

* Offline build

* .

* .

* Merge from upstream

* Reverting dirty commits for custom pipeline scripts.

* Run Build via build script.

* Refer custom task from application source code.

* Update unit test and code coverage task

* Customize code coverage task

* .

* Externalize deploy application script.

* Refer to application repository in deployment pipeline.

* Add app repository to deployment pipeline.

* Externalize deployment tasks.

* Modify acceptance test task to mount repo

* Pass value to statuses to rollback task

* Add output workspace to acceptance task

* Externalize build-artifact-info step

* Externalize build-artifact-info task

* Disable evaluate-gate-task

* Update from anamika's branch

* Change the evaluate gate task

* Bring all custom scripts to pipeline code.

* Update pipeline code to refer to scripts.

* Update the code.

* .

* .

* .

* .

* rename scripts folder to .scripts

* Cleanup scripts

* Added scripts folder

* .

* .

* Add all the scripts file to scripts folder.

* Change the deploy pipeline

* Pass the pipeline repo url

* Update remote deploy script with appropriate repository

* Modifying rollback script execution

* .

* .

* Rename the inventory repository and pipeline repository variable

* Move java specific scripts to corresponding folder.

* Modify build pipeline to read scripts from runtime folder.

* Change the reference name.

* .

* Update the task reference.

* .

* Correct the path for build-artifacts-info

* Change the deploy pipeline script.

* .

* .

* Remove unwanted scripts.

Co-authored-by: Anamika Agrawal <78848657+anamikaagrawal123@users.noreply.github.com>
Co-authored-by: akshaykumar-vijapur <80688656+akshaykumar-vijapur@users.noreply.github.com>

diff --git a/.build_pipeline/task.yaml b/.build_pipeline/task.yaml
--- a/.build_pipeline/task.yaml
+++ b/.build_pipeline/task.yaml
@@ -8,7 +8,9 @@ spec:
       description: The Git Repository for the Application Source Code
       default: repository
     - name: appname
-      description: The name of the application passed as environment variable 
+      description: The name of the application passed as environment variable
+    - name: runtime
+      description: The application lanugage runtime  
   workspaces:
     - name: output
       description: A workspace to store the output of intermittent steps
@@ -27,24 +29,13 @@ spec:
           value: $(params.appname)
         - name: REPOSITORY
           value: $(params.repository)
+        - name: RUNTIME
+          value: $(params.runtime) 
       script: |          
           #!/bin/bash
           set -e -o pipefail;
-
-          # This step creates an archive/zip of your artifacts (source code, binaries, images, configuration files etc.) placed in the
-          # /output/binaries folder to prepare for the upload in the subsequent step. While it creates the archive/zip, it also calculates
-          # the checksum of the archived/zipped contents which will be part of the build metadata to be validated during the download.
+          source ./pipeline-repo/scripts/${RUNTIME}/build-artifact-info.sh
           
-          cd binaries
-          mv *.jar ${APPNAME}.jar
-          
-          OBJECTNAME=binary-`date '+%Y%m%d%H%M%S'`.tar.gz
-          tar -cf ${OBJECTNAME} *
-          echo "Object Name of the archive prepared for upload is" ${OBJECTNAME}
-          
-          CHECKSUM=`md5sum $OBJECTNAME | awk '{ print $1 }'`
-          echo "Checksum of the archive prepared for upload is" ${CHECKSUM}
-
           # OJBECTNAME and CHECKSUM are the result of this task and will be passed down the pipeline to downstream task for processing.
           # The lines below pass on the values of these variables to the results of the task in the format results.<result-name>.path.        
           echo -n "${OBJECTNAME}" > $(results.objectname.path)
@@ -178,17 +169,28 @@ spec:
           #
           # Function to check if the Cloud Object Storage Instance exists in the REGION
           # If not then the function creates a new bucket with name COSBUCKETNAME in the COS Service Instance with name INSTANCENAME
-          # 
+          # 1. User does not have any COS instance, Toolchain will create a COS instance in Lite Plan with same name as toolchain name and use it for creating the bucket.
+          # 2. User has only one COS Instance, The user could be on Lite Plan. We will reuse the same instance for the creating the bucket.
+          # 3. User has two or more COS Instances, Create a COS instance where the name of the instance will be same as the toolchain name and use it for creating the bucket. This will help the user to easily identify the bucket in which the artifacts will be stored.
           CheckAndCreateCOSInstance() {
             COS_INSTANCE_COUNT=$(ibmcloud resource service-instances --service-name cloud-object-storage | awk {'print $1'} | awk 'NR>3' | wc -l)
             if [ "$COS_INSTANCE_COUNT" -eq "1" ]; then
-              echo "Cloud Object Storage Instance already exists."
-              INSTANCENAME=$(ibmcloud resource service-instances --output JSON  --service-name cloud-object-storage | jq .[0] | jq -r .name)
-            else
-              echo "Cloud Object Storage Instance does not exist. Proceeding with creation."
+              INSTANCENAME=$(ibmcloud resource service-instances --output JSON --service-name cloud-object-storage | jq .[0] | jq -r .name)
+              echo "${INSTANCENAME} will be used to create the bucket."
+            elif [ "$COS_INSTANCE_COUNT" -eq "0" ]; then
               INSTANCENAME=$COSBUCKETNAME
-              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage lite global
-            fi                
+              {
+              echo "Cloud Object Storage Instance does not exist. Proceeding with creation of Cloud Object Storage Instance named "$INSTANCENAME" under Lite plan.";
+              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage lite global && echo "Instance creation successfull.."
+              } || {
+              echo "Failed to create an instance with Lite plan. Proceeding with creation of Cloud Object Storage Instance named "$INSTANCENAME" under Standard plan.";
+              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage standard global && echo "Instance creation successfull.."
+              }
+            else
+              INSTANCENAME=$COSBUCKETNAME
+              echo "Multiple Cloud object storage instance detected. Proceeding with creation of instance named ${INSTANCENAME} with standard plan."
+              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage standard global
+            fi
           }
 
           #
